name: Ruby on Rails CI
on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
      CI: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install dependencies
        run: |
          yarn install
          bundle install

      - name: Set up database
        run: |
          bin/rails db:create
          bin/rails db:migrate
          bin/rails db:test:prepare


      - name: Run tests
        run: bin/rake

      - name: Code Coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true 